workflows:
  build_dylib:
    name: Build Dylib
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Set up build environment
        script: |
          # Create necessary directories
          mkdir -p FloatingButton
      - name: Copy files
        script: |
          # Copy your source files into the build directory
          cp FloatingButton.h FloatingButton.m DylibLoader.m FloatingButton/
      - name: Build dylib
        script: |
          cd FloatingButton
          xcrun -sdk iphoneos clang -arch arm64 -dynamiclib -framework UIKit FloatingButton.m DylibLoader.m -o libFloatingButton.dylib
    artifacts:
      - FloatingButton/libFloatingButton.dylib
