name: Build dylib

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          xcode-select --install

      - name: Build dylib
        run: |
          clang -dynamiclib -o libtest.dylib floatingButton.m -framework UIKit -framework Foundation

      - name: Upload dylib
        uses: actions/upload-artifact@v3
        with:
          name: dylib-file
          path: libtest.dylib
